spring:
  application:
    name: ifit-dashboard
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
  
server:
  port: ${SERVER_PORT}

logging:
  level:
    curihous.ifit: ${LOG_LEVEL}
    org.springframework.security: ${SECURITY_LOG_LEVEL}
    org.hibernate.SQL: ${SQL_LOG_LEVEL}
